### ISSUE TITLE
Coding with real components in Angular

### ISSUE THREAD

**Issue by ardiadrianadri** [angularbeers/community-days#1]
Angular doesn't have component. There are some clases with a tag call it "@component" but actually, they are not components because they are tide at one context. However, I've been working in a way to code real components in Angular; pieces of software that are independent of the context and they can work in different platforms. 

The idea of this conference is to share my idea of components and to show you how you can code components in Angular that can be reuse in a wide number of different projects

**Comment by davidpich** [comment]
Hi @ardiadrianadri , can you share your slides here? Thanks!
