### ISSUE TITLE
Boost your Angular app with Web Workers the easy way

### ISSUE THREAD

**Issue by kaikcreator** [angularbeers/community-days#12]
In this talk we'll discuss about the new approach to WebWorkers introduced by Angular, and how you can benefit from this hidden killer feature. We will go through the step-by-step details on how to modify your current angular app to use WebWorkers at a global level with very low effort.

Estimated time 45 min.

**Comment by davidpich** [comment]
Hi @kaikcreator, can you share your slides here? Thanks!

**Comment by kaikcreator** [comment]
For sure!!! https://docs.google.com/presentation/d/1AYkQhU2L7k0k7B8_cKn4G1UIlg8Sw31V-8LccDw4E4g/pub?start=false&loop=false&delayms=3000
