### ISSUE TITLE
From Redux to Ngrx/store

### ISSUE THREAD

**Issue by shprink** [angularbeers/community-days#15]
![image](https://cloud.githubusercontent.com/assets/1388706/23960775/287dded0-09a9-11e7-8e56-b2bb382c8643.png)

ngrx/store is an RxJS powered state management inspired by Redux for Angular applications.

If you already know Redux and start a new Angular project you might wonder what's the best choice between using a library of bindings for Redux or directly ngrx/store.

As it is a bit of a mind shift, this talk explain the transition from Redux to ngrx/store where everything is an Observable!

Duration: ~30min

**Comment by davidpich** [comment]
Hi @shprink, can you share your slides here? Thanks!

**Comment by shprink** [comment]
https://julienrenaux.fr/talks-src/2017/from-redux-to-ngrxstore/#/
