### ISSUE TITLE
Call for speakers?

### ISSUE THREAD

**Issue by rgranadosd** [angularbeers/community-days#16]
Hi angularbeers,

Last year we were working in a refactoring project for our web site desigual.com.  I think it's one of the few webs of the fashion retail  that are developed in angular.
The challenge was to incresase web performance at least 50%. For this purpose we used the speedindex kpi proposed in  webpagetest.com.

Finally we get the goal and we would like to share it with the community.

Are there any chance to do it in this event?

Let me know

Best regards

**Comment by davidpich** [comment]
Hi Rafa! Please contact us at hello@angularbeers.org
