### ISSUE TITLE
Thinking about performance 

### ISSUE THREAD

**Issue by rgranadosd** [angularbeers/community-days#17]
An e-commerce  development is a way of thinking  , we have to think how to transform each second in money. Therefore, we must develop always keeping in mind the  performance.
Here we’ll show how we have applied a refactor oriented to high availability, performance and thus improve user experience.
We will show how we have applied a refactor oriented to high availability, performance and thus improve the user experience.      
 
Our secret ??... Isomorphic architecture, SPA + landings, speed index, clean code, lazy load …​

**Comment by davidpich** [comment]
Hi Rafa @rgranadosd , can you share your slides here? Thanks!
