### ISSUE TITLE
Best Practices on Developing Rich UI Components for Angular

### ISSUE THREAD

**Issue by cagataycivici** [angularbeers/community-days#2]
"This talk covers how to create rich UI components with Angular following the best practices and avoiding the pitfalls. For each practice, a real-life example from PrimeNG will be used as a case-study such as change detection techniques, templating, integrating 3rd party libraries, styling, querying and effective dom handling."

Estimated time is 40 minutes.

**Comment by davidpich** [comment]
Hi @cagataycivici , can you share your slides here? Thanks!

**Comment by cagataycivici** [comment]
Sure;

http://www.slideshare.net/cagataycivici/best-practices-on-developing-rich-ui-components-for-angular
