### ISSUE TITLE
Typesafe Reactive WebComponents

### ISSUE THREAD

**Issue by Hotell** [angularbeers/community-days#4]
You know the drill right? new sexy framework appears... boom new Datepicker in that framework follows and so on.... 

It's 2017 and it's time to stop this madness! How you ask?

In this talk I will do a overview of component creation in terms of re-usability followed up with real life examples how to create modern super performant, small, typesafe, reusable reactive web components.

And no I wont be talking about Polymer ;) 

P.S.: "Don't Hate, just Skate!"

#typescript #virtualDom #skatejs

**Comment by davidpich** [comment]
Hi @Hotell , can you share your slides here? Thanks!

**Comment by Hotell** [comment]
Heyo! sure

https://github.com/Hotell/angular-skate-talk-demo
