### ISSUE TITLE
Compodoc - The ultimate documentation tool for your Angular application

### ISSUE THREAD

**Issue by vogloblinsky** [angularbeers/community-days#5]
Documentation ! With testing, it is the two first items dropped when project fall late. It takes time to write and maintain, it can be quickly outdated, or incomplete. In short, documentation is always a boring task for developers, and we rather prefer coding.

Compodoc comes in the “Living documentation” movement by providing a tool for Angular developers which they can integrate in their toolset for auto-generating documentation with ease.
Compodoc recognises every Angular API (modules, components, directives, …), with JSDoc comments blocs, and more.

Do you care about documentation? Come discover during this new tool and all of its features for your Angular projects.

https://github.com/compodoc/compodoc

**Comment by davidpich** [comment]
Hi @vogloblinsky , can you share your slides here? Thanks!

**Comment by vogloblinsky** [comment]
Yes !
http://slides.com/vogloblinsky/compodoc-the-missing-documentation-tool-for-your-angular-application
