### ISSUE TITLE
WordPress + Ionic2 = <3

### ISSUE THREAD

**Issue by shprink** [angularbeers/community-days#8]
WordPress powers 25% of the web nowadays. Since WP 4.7 a RESTFUL Web Service is available to query any resources. For instance getting the latests posts is as simple as querying https://dev.julienrenaux.fr/wp-json/wp/v2/posts

This talk will be about [WordPress Hybrid Client](https://github.com/shprink/wordpress-hybrid-client) a Ionic2 client that helps you build WordPress based PWA, iOS, Android & Windows phones apps in minutes!

![image](https://cloud.githubusercontent.com/assets/1388706/23603012/7c1b1470-0253-11e7-9714-8e77a397a274.png)

**Comment by davidpich** [comment]
Hi @shprink , can you share your slides here? Thanks!

**Comment by shprink** [comment]
https://julienrenaux.fr/talks-src/2017/from-redux-to-ngrxstore/#/
