### ISSUE TITLE
PrimeNG Workshop

### ISSUE THREAD

**Issue by cagataycivici** [angularbeers/community-days#9]
"PrimeNG is a popular open source UI component suite for Angular with over 70 components. In this workshop, we'll create a sample CRUD application with PrimeNG using various components like forms, datatable, dialog and more. The sample application will use the Ultima theme of PrimeNG as the template". 

- Estimated time is 2h.

**Comment by davidpich** [comment]
Hi @cagataycivici , can you share your slides here? Thanks!
